import telebot
from telebot import types
bot = telebot.TeleBot('7825701501:AAGcXwKM4uI2XIwXB_wVQrxRMzZjz4fj1N0')
@bot.message_handler(commands=['start'])
def start(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    btn1 = types.KeyboardButton("Q&A")
    btn2 = types.KeyboardButton("Справки")
    btn3 = types.KeyboardButton("Расписания")
    btn4 = types.KeyboardButton('Заявления')
    markup.add(btn1, btn2, btn3, btn4)
    bot.send_message(message.chat.id,
                     text="Привет, {0.first_name}! Я тестовый бот".format(
                         message.from_user), reply_markup=markup)
@bot.message_handler(content_types=['text'])
def func(message):
    if (message.text == "Справки"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn1 = types.KeyboardButton("Медецинская")
        btn2 = types.KeyboardButton("Об обучении")
        back = types.KeyboardButton("Вернуться в главное меню")
        markup.add(btn1, btn2, back)
        bot.send_message(message.chat.id, text="...", reply_markup=markup)
    elif (message.text == "Q&A"):
        bot.send_message(message.chat.id, text="Пока нету")
    elif (message.text == "Расписания"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn1 = types.KeyboardButton("1-4 класс")
        btn2 = types.KeyboardButton("5-8 класс")
        btn3 = types.KeyboardButton("9-11 класс")
        btn4 = types.KeyboardButton("Звонки")
        back = types.KeyboardButton("Каникулы")
        abc = types.KeyboardButton("Вернуться в главное меню")
        markup.add(btn1, btn2, btn3, btn4, back, abc)
        bot.send_message(message.chat.id, text="...", reply_markup=markup)
    elif (message.text == "Заявления"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn1 = types.KeyboardButton("Освобождение от занятий")
        btn2 = types.KeyboardButton("Смена учебного формата")
        btn3 = types.KeyboardButton("Отчисление из школы")
        btn4 = types.KeyboardButton("Зачисление в 1 класс")
        btn5 = types.KeyboardButton("Переход на льготное или платное питание")
        btn6 = types.KeyboardButton("Прохождение аттестации экстерном")
        abc = types.KeyboardButton("Вернуться в главное меню")
        markup.add(btn1, btn2, btn3, btn4, btn5, btn6, abc)
        bot.send_message(message.chat.id, text="...", reply_markup=markup)
    elif (message.text == "Вернуться в главное меню"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        button1 = types.KeyboardButton("Q&A")
        button2 = types.KeyboardButton("Справки")
        button3 = types.KeyboardButton("Расписания")
        markup.add(button1, button2, button3)
        bot.send_message(message.chat.id, text="Вы вернулись в главное меню", reply_markup=markup)
    elif (message.text == "1-4 класс"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        button1 = types.KeyboardButton("1A")
        button2 = types.KeyboardButton("2А")
        button3 = types.KeyboardButton("3А")
        button4 = types.KeyboardButton("4А")
        button5 = types.KeyboardButton("1Б")
        button6 = types.KeyboardButton("2Б")
        button7 = types.KeyboardButton("3Б")
        button8 = types.KeyboardButton("4Б")
        button9 = types.KeyboardButton("1В")
        button10 = types.KeyboardButton("2В")
        button11 = types.KeyboardButton("3В")
        button12 = types.KeyboardButton("4В")
        back = types.KeyboardButton("Вернуться в главное меню")
        markup.add(button1, button2, button3, button4, button5, button6, button7, button8, button9, button10, button11, button12, back)
        bot.send_message(message.chat.id, text="Вы вернулись в главное меню", reply_markup=markup)
    elif (message.text == "5-8 класс"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        button1 = types.KeyboardButton("5A")
        button2 = types.KeyboardButton("6А")
        button3 = types.KeyboardButton("7А")
        button4 = types.KeyboardButton("8А")
        button5 = types.KeyboardButton("5Б")
        button6 = types.KeyboardButton("6Б")
        button7 = types.KeyboardButton("7Б")
        button8 = types.KeyboardButton("8Б")
        button9 = types.KeyboardButton("5В")
        button10 = types.KeyboardButton("6В")
        button11 = types.KeyboardButton("7В")
        back = types.KeyboardButton("Вернуться в главное меню")
        markup.add(button1, button2, button3, button4, button5, button6, button7, button8, button9, button10, button11, back)
        bot.send_message(message.chat.id, text="...", reply_markup=markup)
    elif (message.text == "9-11 класс"):
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        button1 = types.KeyboardButton("9A")
        button2 = types.KeyboardButton("10А")
        button3 = types.KeyboardButton("11А")
        button5 = types.KeyboardButton("9Б")
        button6 = types.KeyboardButton("10Б")
        button7 = types.KeyboardButton("11Б")
        back = types.KeyboardButton("Вернуться в главное меню")
        markup.add(button1, button2, button3, button5, button6, button7, back)
        bot.send_message(message.chat.id, text="...", reply_markup=markup)
    else:
        bot.send_message(message.chat.id, text="На такую комманду я не запрограммировал..")
bot.polling(none_stop=True)